'use client';

import { useEffect, useState } from 'react';
interface UserRow { userId: string; maskedEmail: string | null; username: string | null; role: 'user' | 'moderator' | 'admin'; accountStatus: 'active' | 'suspended' | 'anonymized'; governanceVersion: number; emailVerified: boolean; createdAt: string }

export default function UsersManager() {
  const [items, setItems] = useState<UserRow[]>([]); const [q, setQ] = useState(''); const [reason, setReason] = useState(''); const [confirmation, setConfirmation] = useState(''); const [message, setMessage] = useState<string | null>(null);
  const load = async (search = q) => { const response = await fetch(`/api/admin/users?q=${encodeURIComponent(search)}`); const body = await response.json(); if (response.ok) setItems(body.items); else setMessage(body?.error?.message ?? '加载失败'); };
  useEffect(() => { let active = true; void fetch('/api/admin/users').then(async (response) => { const body = await response.json(); if (active && response.ok) setItems(body.items); }); return () => { active = false; }; }, []);
  const update = async (user: UserRow, change: { role?: UserRow['role']; accountStatus?: 'active' | 'suspended' }) => {
    const response = await fetch(`/api/admin/users/${user.userId}`, { method: 'PATCH', headers: { 'content-type': 'application/json', 'idempotency-key': crypto.randomUUID() }, body: JSON.stringify({ ...change, expectedVersion: user.governanceVersion, targetConfirmation: confirmation, reason }) });
    const body = await response.json().catch(() => null); setMessage(response.ok ? '账号状态已更新，目标账号会话已全部撤销。' : body?.error?.message ?? '更新失败'); if (response.ok) { setConfirmation(''); await load(); }
  };
  return <section className="admin-panel"><header><h2>账号与角色</h2><span>{items.length}</span></header><div className="admin-form-stack user-filters"><label>搜索<input value={q} onChange={(event) => setQ(event.target.value)} /></label><button type="button" className="btn-secondary" onClick={() => void load()}>查询</button><label>操作理由<input value={reason} maxLength={500} onChange={(event) => setReason(event.target.value)} /></label><label>目标 userId 二次确认<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} /></label></div>{message && <p className="notice" role="status">{message}</p>}<div className="admin-table-scroll"><table><thead><tr><th>账号</th><th>角色</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map((user) => <tr key={user.userId}><td><strong>{user.username || user.maskedEmail || '已注销用户'}</strong><small className="mono-id">{user.userId}</small></td><td>{user.role}</td><td>{user.accountStatus}{!user.emailVerified && ' · 未验证'}</td><td><div className="table-actions"><button type="button" disabled={reason.trim().length < 3 || confirmation !== user.userId || user.accountStatus === 'anonymized'} onClick={() => void update(user, { role: user.role === 'user' ? 'moderator' : 'user' })}>{user.role === 'user' ? '设为版主' : '降为用户'}</button><button type="button" disabled={reason.trim().length < 3 || confirmation !== user.userId || user.accountStatus === 'anonymized'} onClick={() => void update(user, { accountStatus: user.accountStatus === 'suspended' ? 'active' : 'suspended' })}>{user.accountStatus === 'suspended' ? '恢复' : '暂停'}</button></div></td></tr>)}</tbody></table></div></section>;
}
